spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/petking?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 20
      minimum-idle: 10

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: false
    open-in-view: false

  redis:
    host: localhost
    port: 6379
    password: "#{null}"
    ssl: false
    jedis:
      pool:
        max-active: 20
        max-idle: 8
        max-wait: 5000
        min-idle: 4
    timeout: 5000
  sql:
    init:
      encoding: UTF-8

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 909362200876-dpe2kdq02ahj8cn1030mut6p2db5rnrl.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

#logging:
#  level:
#    org.springframework: info
#    com.onthe7.petking: debug
#  file:
#    path: /LogFiles