server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081
spring:
  output:
    ansi:
      enabled: detect
  data:
    web:
      pageable:
        one-indexed-parameters: true

---

spring.profiles: local

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/petking?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 20
      minimum-idle: 10
    sql-script-encoding: UTF-8

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: false
    open-in-view: false

  redis:
    host: localhost
    port: 6379
    password: "#{null}"
    ssl: false
    cache_database: 1
    jedis:
      pool:
        max-active: 20
        max-idle: 8
        max-wait: 5000
        min-idle: 4
    timeout: 5000

logging:
  level:
    org.springframework: info
    io.lpin.kdn: debug
  file:
    path: /LogFiles
